title: struggle.zone
email: eski@struggle.zone
description: LBLB - IT solutions
baseurl: ''
url: ''
title_description: >-
  Willkommen zu unserem gesammelten Wissen.
title_image: 'https://i.imgur.com/q1KfdiL.png'
google_analytics: UA-20365477-4
disqus_account: cartenoire
github_repository: 'https://github.com/jacobtomlinson/carte-noire'
addthis_id: ra-513c6fa83da6ec67
post_limit: 5
twitter_username: lukasdmo
github_username: null
instagram_username: null
reddit_username: null
linkedin_link: null
google_plus_link: null
stackoverflow_link: null
xing_link: null
facebook_link: null
footer_left: >-
  Made by
  <a href="https://twitter.com/lukasdmo"> LBLB</a>
footer_right: >-
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
exclude:
  - vendor
