title: LBLB - IT
email: eski@struggle.zone
description: LBLB - IT solutions
baseurl: ''
url: ''
title_description: >-
  Willkommen zu unserem gesammelten Wissen.
title_image: 'https://i.imgur.com/GDlOYYr.png'
google_analytics: UA-20365477-4
disqus_account: cartenoire
github_repository: 'https://github.com/jacobtomlinson/carte-noire'
addthis_id: ra-513c6fa83da6ec67
post_limit: 5
twitter_username: lukasdmo

footer_left: >-
  Made by
  <a href="https://twitter.com/lukasdmo"> LBLB</a>
footer_right: >-
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
exclude:
  - vendor
